# Generated by Django 2.0.4 on 2018-05-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=50)),
                ('data_med', models.DateTimeField(verbose_name='data da med')),
                ('valor', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
